name: Build Android APK

on:
  workflow_dispatch: # Cho phép bấm chạy thủ công trên GitHub
  push:
    branches: [ "main", "master" ] # Tự động chạy ngay khi đẩy code lên nhánh main hoặc master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cài đặt Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Cài đặt Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Cài đặt thư viện Capacitor
        run: |
          rm -rf node_modules
          npm install
          mkdir -p www
          echo "" > www/index.html
          npx cap sync android
        
      - name: Build APK (Sử dụng máy chủ GitHub)
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug
          
      - name: Trả về file APK cho bạn tải xuống
        uses: actions/upload-artifact@v4
        with:
          name: WearConnect-App
          path: android/app/build/outputs/apk/debug/app-debug.apk